TWITTER_APP_ID: '12288796'
TWITTER_CONSUMER_KEY: '08eVz6MzaHQlXjWCaNsOnje3Z'
TWITTER_CONSUMER_SECRET: 'gU3efQa34BEYPgs8THtYqsbXwHAYlj9gDRw4DfzXjcfvZ7VPny'
TWITTER_ACCESS_TOKEN: '2333158698-kWd0IWqRVQO6Mib4IKQMSVXb6zCUgYHFHyLgPKo'
TWITTER_ACCESS_SECRET: 'adG2sEHxXjUifdfC2Ykfkk7jNaljE5yPlTijsq95cVGPE'
TWITTER_BEARER_TOKEN: 'AAAAAAAAAAAAAAAAAAAAAByDuwAAAAAAIB91tZ8j8UNEqnK0g34gCuvSAp8%3DEDtLmUDyBadq
HRQTAi9MW9hkE4TYmo4qCsQtHG5NvOU5GH77x3'
RATE_LIMIT: 450
MINUTES: 15